apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: docker-puller
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: docker-puller
  template:
    metadata:
      labels:
        name: docker-puller
    spec:
      containers:
        - name: docker-puller
          image: portworx/docker-puller:latest
          imagePullPolicy: Always
          args:
          - "-i"
          - "harshpx/px:dev"
          - "-w"
          readinessProbe:
            exec:
              command:
              - cat
              - /tmp/docker-pull-done
          volumeMounts:
            - name: varrun
              mountPath: /var/run/
      restartPolicy: Always
      volumes:
        - name: varrun
          hostPath:
            path: /var/run/
